import Header from './(components)/Header'
import './globals.css'
import Providers from './providers';
import Footer from './(components)/Footer';
import { Montserrat } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font=mont"
})

export default async function RootLayout({
  children,
}: {
    children: React.ReactNode
  }) {
  
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-mont bg-light px-32`}>
        <Providers> 
          <Header />    
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
